//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace slcm {
    
    
    public partial class index {
        
        protected System.Web.UI.HtmlControls.HtmlForm loginForm;
        
        protected System.Web.UI.HtmlControls.HtmlInputText username;
        
        protected System.Web.UI.HtmlControls.HtmlInputText password;
        
        protected System.Web.UI.HtmlControls.HtmlGenericControl message;
        
        protected System.Web.UI.HtmlControls.HtmlInputText usernameRegister;
        
        protected System.Web.UI.HtmlControls.HtmlInputText passwordRegister;
    }
}
